
package presentacion;

/**
 * Dashboard web mejorado.
 *
 * Mejoras incluidas:
 * 1. Sonido corto por cada nueva entrada detectada.
 * 2. Panel en tiempo real de ingresos detectados.
 * 3. Graficas de distancia y ocupacion sin librerias externas.
 * 4. Indicadores KPI mas visuales.
 * 5. Mejor estructura visual, tarjetas, tablas y timeline.
 *
 * Nota tecnica importante:
 * Con HC-SR04 solo puedes detectar presencia/distancia y estimar un ingreso.
 * NO puedes saber "quien" entro realmente sin hardware adicional
 * como RFID, QR, camara o biometria.
 */
final class DashboardHtml {
    private DashboardHtml() {}

    static final String PAGE = ""
            + "<!DOCTYPE html>\n"
            + "<html lang=\"es\">\n"
            + "<head>\n"
            + "<meta charset=\"UTF-8\">\n"
            + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
            + "<title>Estadio Inteligente - Dashboard Pro</title>\n"
            + "<style>\n"
            + "  :root{--sky:#03111f;--sky2:#081c33;--field:#0f3d1e;--field2:#175c2d;--turf:#1f7a3a;"
            + "        --line:#e8f5e9;--flood:#ffb300;--flood2:#ffd54f;--crimson:#e53935;--crimson2:#ff5252;"
            + "        --royal:#1565c0;--royal2:#42a5f5;--gold:#ffd700;--mint:#76ff03;"
            + "        --card:rgba(10,30,18,.92);--border:rgba(255,215,0,.28);--text:#f1f8e9;--muted:#b4c6b6;"
            + "        --accent:var(--flood2);--accent2:var(--mint);--green:var(--mint);--orange:var(--flood);"
            + "        --red:var(--crimson2);--cyan:var(--royal2);--purple:var(--gold);--yellow:var(--flood2);}\n"
            + "  *{margin:0;padding:0;box-sizing:border-box;}\n"
            + "  body{font-family:'Segoe UI',system-ui,sans-serif;"
            + "       background:radial-gradient(ellipse at 20% 0%, rgba(255,179,0,.18), transparent 35%),"
            + "                  radial-gradient(ellipse at 80% 0%, rgba(21,101,192,.22), transparent 35%),"
            + "                  linear-gradient(180deg,#03111f 0%,#081c33 22%,#0f3d1e 55%,#0a2913 100%);"
            + "       color:var(--text);padding:20px;max-width:1440px;margin:0 auto;min-height:100vh;}\n"
            + "  header{padding:28px 20px;border:1px solid rgba(255,215,0,.32);border-radius:18px;"
            + "       background:linear-gradient(135deg,rgba(15,61,30,.78),rgba(21,101,192,.45)),"
            + "                  repeating-linear-gradient(90deg,rgba(232,245,233,.08) 0 2px,transparent 2px 72px),"
            + "                  radial-gradient(circle at 15% 0%, rgba(255,179,0,.38), transparent 42%),"
            + "                  radial-gradient(circle at 85% 0%, rgba(255,179,0,.38), transparent 42%);"
            + "       margin-bottom:22px;box-shadow:0 10px 30px rgba(0,0,0,.45), inset 0 0 40px rgba(255,215,0,.08);} \n"
            + "  .header-top{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap;}\n"
            + "  h1{font-size:2.1rem;color:var(--flood2);margin-bottom:6px;text-shadow:0 0 18px rgba(255,179,0,.45), 0 2px 0 rgba(0,0,0,.4);letter-spacing:.5px;}\n"
            + "  .subtitle{color:var(--line);font-size:.98rem;opacity:.85;}\n"
            + "  .status-bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-top:14px;}\n"
            + "  .badge{display:inline-flex;align-items:center;gap:8px;padding:8px 14px;border-radius:999px;"
            + "       background:rgba(3,17,31,.72);border:1px solid rgba(255,215,0,.28);font-size:.88rem;backdrop-filter:blur(4px);} \n"
            + "  .dot{width:10px;height:10px;border-radius:50%;background:var(--muted);box-shadow:0 0 10px transparent;}\n"
            + "  .dot.on{background:var(--mint);box-shadow:0 0 14px var(--mint);}\n"
            + "  .dot.off{background:var(--crimson);box-shadow:0 0 14px var(--crimson);}\n"
            + "  .dot.warn{background:var(--flood);box-shadow:0 0 14px var(--flood);}\n"
            + "  .hero-metrics{display:flex;gap:12px;flex-wrap:wrap;}\n"
            + "  .hero-pill{padding:10px 14px;border-radius:14px;background:rgba(3,17,31,.78);border:1px solid rgba(255,215,0,.3);min-width:140px;box-shadow:inset 0 0 22px rgba(255,179,0,.08);} \n"
            + "  .hero-pill .label{font-size:.75rem;color:var(--flood2);text-transform:uppercase;letter-spacing:1.5px;}\n"
            + "  .hero-pill .num{font-size:1.45rem;font-weight:800;margin-top:4px;color:var(--line);text-shadow:0 0 12px rgba(255,215,0,.4);}\n"
            + "\n"
            + "  .kpi-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;margin-bottom:20px;}\n"
            + "  .card{background:linear-gradient(180deg,rgba(15,61,30,.88),rgba(3,17,31,.92));border:1px solid rgba(255,215,0,.22);border-radius:18px;padding:18px;"
            + "       box-shadow:0 12px 28px rgba(0,0,0,.38), inset 0 1px 0 rgba(255,215,0,.08);transition:transform .15s ease,border-color .15s ease,box-shadow .2s ease;position:relative;overflow:hidden;}"
            + "  .card::before{content:'';position:absolute;top:-35%;right:-8%;width:60%;height:72%;background:radial-gradient(circle, rgba(255,179,0,.18), transparent 68%);pointer-events:none;} \n"
            + "  .card::after{content:'';position:absolute;bottom:0;left:0;right:0;height:3px;background:linear-gradient(90deg,var(--crimson),var(--flood),var(--mint),var(--royal2));opacity:.55;}\n"
            + "  .card:hover{transform:translateY(-2px);border-color:var(--flood2);box-shadow:0 14px 32px rgba(0,0,0,.45), 0 0 0 1px rgba(255,179,0,.25);}\n"
            + "  .card h2,.section h3{font-size:.82rem;letter-spacing:1.5px;text-transform:uppercase;color:var(--flood2);margin-bottom:10px;}\n"
            + "  .value{font-size:2.3rem;font-weight:800;line-height:1;color:var(--line);text-shadow:0 0 14px rgba(255,215,0,.35);}\n"
            + "  .unit{font-size:.42em;color:var(--muted);font-weight:500;margin-left:4px;}\n"
            + "  .sub{margin-top:8px;color:var(--muted);font-size:.93rem;}\n"
            + "  .bar{height:10px;background:#03111f;border-radius:999px;overflow:hidden;margin-top:12px;border:1px solid rgba(255,215,0,.18);}\n"
            + "  .bar > span{display:block;height:100%;width:0%;transition:width .45s ease;background:linear-gradient(90deg,var(--mint),var(--flood2));}\n"
            + "  .bar.green > span{background:linear-gradient(90deg,var(--turf),var(--mint));}\n"
            + "  .bar.orange > span{background:linear-gradient(90deg,var(--flood),var(--gold));}\n"
            + "  .bar.red > span{background:linear-gradient(90deg,var(--crimson),var(--flood));}\n"
            + "  .chip{display:inline-flex;align-items:center;padding:5px 10px;border-radius:999px;font-size:.76rem;border:1px solid var(--border);background:rgba(3,17,31,.8);color:var(--flood2);}\n"
            + "  .chip.on{color:var(--mint);border-color:rgba(118,255,3,.45);background:rgba(15,61,30,.6);}\n"
            + "  .chip.off{color:var(--muted);}\n"
            + "  .green .value{color:var(--mint);}\n"
            + "  .orange .value{color:var(--flood2);}\n"
            + "  .red .value{color:var(--crimson2);}\n"
            + "  .purple .value{color:var(--gold);}\n"
            + "\n"
            + "  .layout{display:grid;grid-template-columns:1.45fr .95fr;gap:18px;margin-bottom:20px;}\n"
            + "  @media (max-width:1100px){.layout{grid-template-columns:1fr;}}\n"
            + "\n"
            + "  .section{background:linear-gradient(180deg,rgba(15,61,30,.82),rgba(3,17,31,.94));border:1px solid rgba(255,215,0,.22);border-radius:18px;padding:18px;box-shadow:0 12px 24px rgba(0,0,0,.38);position:relative;overflow:hidden;}"
            + "  .section::before{content:'';position:absolute;top:-38%;right:-10%;width:50%;height:70%;background:radial-gradient(circle, rgba(255,179,0,.16), transparent 72%);pointer-events:none;} \n"
            + "  .section-header{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:12px;border-bottom:1px solid rgba(255,215,0,.18);padding-bottom:8px;}\n"
            + "  .canvas-wrap{background:repeating-linear-gradient(90deg,rgba(232,245,233,.04) 0 2px,transparent 2px 40px),linear-gradient(180deg,#0a2913,#061a0c);border:1px solid rgba(255,215,0,.2);border-radius:14px;padding:14px;height:260px;} \n"
            + "  canvas{width:100%;height:100%;display:block;}\n"
            + "\n"
            + "  .event-feed{display:flex;flex-direction:column;gap:10px;max-height:520px;overflow:auto;padding-right:4px;}\n"
            + "  .event-item{display:grid;grid-template-columns:92px 1fr auto;gap:12px;align-items:center;padding:12px;border-radius:14px;"
            + "       background:linear-gradient(135deg,rgba(15,61,30,.9),rgba(21,101,192,.35));border:1px solid rgba(255,215,0,.3);box-shadow:inset 0 0 18px rgba(255,179,0,.08);} \n"
            + "  .event-time{font-family:Consolas,monospace;color:var(--flood2);font-size:.92rem;font-weight:700;} \n"
            + "  .event-main strong{display:block;color:var(--line);font-size:.96rem;margin-bottom:4px;}\n"
            + "  .event-main span{color:var(--muted);font-size:.88rem;}\n"
            + "  .event-tag{padding:6px 10px;border-radius:999px;font-size:.74rem;font-weight:800;border:1px solid var(--border);letter-spacing:.8px;}\n"
            + "  .event-tag.in{color:#03111f;border-color:var(--mint);background:var(--mint);} \n"
            + "  .event-tag.warn{color:#03111f;border-color:var(--flood);background:var(--flood2);} \n"
            + "\n"
            + "  table{width:100%;border-collapse:collapse;}\n"
            + "  th,td{padding:10px 12px;border-bottom:1px solid rgba(255,215,0,.14);text-align:left;font-size:.92rem;}\n"
            + "  th{color:var(--flood2);font-weight:800;background:rgba(3,17,31,.7);text-transform:uppercase;letter-spacing:1px;font-size:.78rem;} \n"
            + "  td{color:var(--line);}\n"
            + "\n"
            + "  .log{background:#020a12;border:1px solid rgba(255,215,0,.22);border-radius:12px;padding:12px;font-family:Consolas,monospace;font-size:.88rem;max-height:240px;overflow-y:auto;}\n"
            + "  .log div{padding:4px 0;border-bottom:1px dashed rgba(255,215,0,.1);word-break:break-word;}\n"
            + "  .time{color:var(--flood2);margin-right:8px;}\n"
            + "  .ok{color:var(--mint);}\n"
            + "  .warn{color:var(--flood2);}\n"
            + "  .err{color:var(--crimson2);}\n"
            + "\n"
            + "  .controls{display:flex;gap:8px;flex-wrap:wrap;}\n"
            + "  .controls input,.controls button{background:rgba(3,17,31,.88);color:var(--text);border:1px solid rgba(255,215,0,.28);border-radius:10px;padding:10px 14px;font-size:.95rem;font-family:inherit;} \n"
            + "  .controls input{flex:1;min-width:220px;}\n"
            + "  .controls button{cursor:pointer;font-weight:800;color:var(--flood2);letter-spacing:.5px;} \n"
            + "  .controls button:hover{border-color:var(--flood2);background:linear-gradient(135deg,rgba(255,179,0,.2),rgba(229,57,53,.18));color:var(--line);} \n"
            + "\n"
            + "  .alarm-box{display:flex;align-items:center;justify-content:space-between;gap:14px;}\n"
            + "  .alarm-state{font-size:1.7rem;font-weight:800;}\n"
            + "  .pulse{animation:pulse 1s infinite;}\n"
            + "  @keyframes pulse{0%{opacity:1;transform:scale(1)}50%{opacity:.55;transform:scale(1.03)}100%{opacity:1;transform:scale(1)}}\n"
            + "  footer{text-align:center;color:var(--muted);font-size:.82rem;padding:18px 4px;}\n"
            + "</style>\n"
            + "</head>\n"
            + "<body>\n"
            + "<header>\n"
            + "  <div class=\"header-top\">\n"
            + "    <div>\n"
            + "      <h1>Estadio Inteligente</h1>\n"
            + "      <div class=\"subtitle\">Centro de monitoreo operativo en tiempo real · Arduino + HC-SR04 + SSD1306</div>\n"
            + "      <div class=\"status-bar\">\n"
            + "        <span class=\"badge\"><span id=\"hwDot\" class=\"dot\"></span><span id=\"hwText\">Conectando...</span></span>\n"
            + "        <span class=\"badge\">Modo: <strong id=\"modeText\">-</strong></span>\n"
            + "        <span class=\"badge\">Ultima lectura: <span id=\"lastUpdate\">-</span></span>\n"
            + "        <span class=\"badge\">Frecuencia: 1s</span>\n"
            + "      </div>\n"
            + "    </div>\n"
            + "    <div class=\"hero-metrics\">\n"
            + "      <div class=\"hero-pill\"><div class=\"label\">Ingresos hoy</div><div class=\"num\" id=\"entriesToday\">0</div></div>\n"
            + "      <div class=\"hero-pill\"><div class=\"label\">Ultimo evento</div><div class=\"num\" id=\"lastEventMini\">-</div></div>\n"
            + "      <div class=\"hero-pill\"><div class=\"label\">Ocupacion</div><div class=\"num\" id=\"occMini\">0%</div></div>\n"
            + "    </div>\n"
            + "  </div>\n"
            + "</header>\n"
            + "\n"
            + "<div class=\"kpi-grid\">\n"
            + "  <div class=\"card\" id=\"cardDistance\">\n"
            + "    <h2>Distancia sensada <span class=\"chip\" id=\"presenceChip\">-</span></h2>\n"
            + "    <div class=\"value\"><span id=\"distance\">--</span><span class=\"unit\">cm</span></div>\n"
            + "    <div class=\"sub\" id=\"distanceDesc\">Sin datos</div>\n"
            + "    <div class=\"bar green\"><span id=\"distanceBar\"></span></div>\n"
            + "  </div>\n"
            + "\n"
            + "  <div class=\"card\" id=\"cardEntry\">\n"
            + "    <h2>Entradas acumuladas</h2>\n"
            + "    <div class=\"value\"><span id=\"entries\">0</span><span class=\"unit\">/ <span id=\"threshold\">100</span></span></div>\n"
            + "    <div class=\"sub\">Capacidad operativa monitoreada</div>\n"
            + "    <div class=\"bar\"><span id=\"entryBar\"></span></div>\n"
            + "  </div>\n"
            + "\n"
            + "  <div class=\"card\" id=\"cardLight\">\n"
            + "    <h2>Luces</h2>\n"
            + "    <div class=\"value\"><span id=\"light\">0</span><span class=\"unit\">%</span></div>\n"
            + "    <div class=\"sub\" id=\"lightState\">Apagadas</div>\n"
            + "    <div class=\"bar orange\"><span id=\"lightBar\"></span></div>\n"
            + "  </div>\n"
            + "\n"
            + "  <div class=\"card\" id=\"cardAlarm\">\n"
            + "    <h2>Alarma</h2>\n"
            + "    <div class=\"alarm-box\">\n"
            + "      <div>\n"
            + "        <div class=\"alarm-state\" id=\"alarm\">OFF</div>\n"
            + "        <div class=\"sub\" id=\"alarmSub\">Sistema normal</div>\n"
            + "      </div>\n"
            + "      <div class=\"chip\" id=\"riskChip\">Riesgo bajo</div>\n"
            + "    </div>\n"
            + "  </div>\n"
            + "</div>\n"
            + "\n"
            + "<div class=\"layout\">\n"
            + "  <div>\n"
            + "    <div class=\"section\" style=\"margin-bottom:18px;\">\n"
            + "      <div class=\"section-header\">\n"
            + "        <h3>Grafica de distancia en tiempo real</h3>\n"
            + "        <span class=\"chip\">Ultimos 30 puntos</span>\n"
            + "      </div>\n"
            + "      <div class=\"canvas-wrap\"><canvas id=\"distanceChart\" width=\"800\" height=\"240\"></canvas></div>\n"
            + "    </div>\n"
            + "\n"
            + "    <div class=\"section\" style=\"margin-bottom:18px;\">\n"
            + "      <div class=\"section-header\">\n"
            + "        <h3>Grafica de ocupacion</h3>\n"
            + "        <span class=\"chip\">Capacidad vs entradas</span>\n"
            + "      </div>\n"
            + "      <div class=\"canvas-wrap\"><canvas id=\"occupancyChart\" width=\"800\" height=\"240\"></canvas></div>\n"
            + "    </div>\n"
            + "\n"
            + "    <div class=\"section\">\n"
            + "      <div class=\"section-header\">\n"
            + "        <h3>Acciones automaticas del sistema</h3>\n"
            + "        <span class=\"chip\">Autolog</span>\n"
            + "      </div>\n"
            + "      <div class=\"log\" id=\"actionsLog\"><div class=\"time\">Esperando datos...</div></div>\n"
            + "    </div>\n"
            + "  </div>\n"
            + "\n"
            + "  <div>\n"
            + "    <div class=\"section\" style=\"margin-bottom:18px;\">\n"
            + "      <div class=\"section-header\">\n"
            + "        <h3>Ingresos detectados en vivo</h3>\n"
            + "        <span class=\"chip\" id=\"liveCounter\">0 eventos</span>\n"
            + "      </div>\n"
            + "      <div class=\"event-feed\" id=\"eventFeed\"></div>\n"
            + "    </div>\n"
            + "\n"
            + "    <div class=\"section\" style=\"margin-bottom:18px;\">\n"
            + "      <div class=\"section-header\">\n"
            + "        <h3>Resumen operativo</h3>\n"
            + "        <span class=\"chip\">Snapshot</span>\n"
            + "      </div>\n"
            + "      <table>\n"
            + "        <thead><tr><th>Indicador</th><th>Valor</th></tr></thead>\n"
            + "        <tbody>\n"
            + "          <tr><td>Presencia actual</td><td id=\"presenceRow\">-</td></tr>\n"
            + "          <tr><td>Ultima distancia</td><td id=\"distanceRow\">-</td></tr>\n"
            + "          <tr><td>Nivel de ocupacion</td><td id=\"occupancyRow\">-</td></tr>\n"
            + "          <tr><td>Luces</td><td id=\"lightRow\">-</td></tr>\n"
            + "          <tr><td>Estado alarma</td><td id=\"alarmRow\">-</td></tr>\n"
            + "        </tbody>\n"
            + "      </table>\n"
            + "    </div>\n"
            + "\n"
            + "    <div class=\"section\">\n"
            + "      <div class=\"section-header\">\n"
            + "        <h3>Consola de comandos</h3>\n"
            + "        <span class=\"chip\">Control manual</span>\n"
            + "      </div>\n"
            + "      <form id=\"cmdForm\" class=\"controls\" onsubmit=\"return sendCommand(event);\">\n"
            + "        <input id=\"cmdInput\" placeholder=\"Ej: READ, LIGHT 80, ALARM ON, MODE AUTO, STATUS, HELP\" autocomplete=\"off\">\n"
            + "        <button type=\"submit\">Enviar</button>\n"
            + "        <button type=\"button\" onclick=\"quick('READ')\">READ</button>\n"
            + "        <button type=\"button\" onclick=\"quick('STATUS')\">STATUS</button>\n"
            + "        <button type=\"button\" onclick=\"quick('HELP')\">HELP</button>\n"
            + "      </form>\n"
            + "      <div class=\"log\" id=\"cmdLog\" style=\"margin-top:12px;\"></div>\n"
            + "    </div>\n"
            + "  </div>\n"
            + "</div>\n"
            + "\n"
            + "<footer>Dashboard actualizado cada segundo · Estadio Inteligente · Version visual ejecutiva</footer>\n"
            + "\n"
            + "<script>\n"
            + "const $ = (id) => document.getElementById(id);\n"
            + "const actionsSeen = new Set();\n"
            + "const liveEvents = [];\n"
            + "const distanceHistory = [];\n"
            + "const occupancyHistory = [];\n"
            + "let prevEntryCount = 0;\n"
            + "let audioCtx = null;\n"
            + "\n"
            + "function fmtTime(ts){ const d = new Date(ts); return d.toLocaleTimeString(); }\n"
            + "function clamp(v,a,b){ return Math.max(a,Math.min(b,v)); }\n"
            + "function esc(s){ return String(s).replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;','\\'':'&#39;'}[c])); }\n"
            + "\n"
            + "function ensureAudio(){\n"
            + "  if(!audioCtx){\n"
            + "    const Ctx = window.AudioContext || window.webkitAudioContext;\n"
            + "    if(Ctx) audioCtx = new Ctx();\n"
            + "  }\n"
            + "}\n"
            + "\n"
            + "function playEntryBeep(){\n"
            + "  try{\n"
            + "    ensureAudio();\n"
            + "    if(!audioCtx) return;\n"
            + "    const now = audioCtx.currentTime;\n"
            + "    const osc = audioCtx.createOscillator();\n"
            + "    const gain = audioCtx.createGain();\n"
            + "    osc.type = 'sine';\n"
            + "    osc.frequency.setValueAtTime(880, now);\n"
            + "    gain.gain.setValueAtTime(0.0001, now);\n"
            + "    gain.gain.exponentialRampToValueAtTime(0.05, now + 0.01);\n"
            + "    gain.gain.exponentialRampToValueAtTime(0.0001, now + 0.12);\n"
            + "    osc.connect(gain); gain.connect(audioCtx.destination);\n"
            + "    osc.start(now); osc.stop(now + 0.13);\n"
            + "  }catch(e){}\n"
            + "}\n"
            + "\n"
            + "async function refresh(){\n"
            + "  try{\n"
            + "    const r = await fetch('/api/status',{cache:'no-store'});\n"
            + "    if(!r.ok) throw new Error('HTTP '+r.status);\n"
            + "    const d = await r.json();\n"
            + "    render(d);\n"
            + "  }catch(e){\n"
            + "    $('hwDot').className = 'dot off';\n"
            + "    $('hwText').textContent = 'Sin conexion al backend';\n"
            + "  }\n"
            + "}\n"
            + "\n"
            + "function render(d){\n"
            + "  $('hwDot').className = 'dot ' + (d.hardwareConnected ? 'on' : 'off');\n"
            + "  $('hwText').textContent = d.hardwareConnected ? 'Hardware conectado' : 'Hardware desconectado';\n"
            + "  $('modeText').textContent = d.mode || '-';\n"
            + "  $('lastUpdate').textContent = fmtTime(d.timestamp);\n"
            + "\n"
            + "  const distanceValue = Number(d.distanceCm || 0);\n"
            + "  const distText = distanceValue >= 999 ? 'Sin objeto' : distanceValue.toFixed(1);\n"
            + "  $('distance').textContent = distText;\n"
            + "  $('distanceDesc').textContent = d.distanceDesc || '-';\n"
            + "  $('distanceRow').textContent = distText + (distanceValue >= 999 ? '' : ' cm');\n"
            + "\n"
            + "  const distPct = distanceValue >= 999 ? 0 : clamp(100 - ((distanceValue / (d.distanceThreshold || 100)) * 100), 0, 100);\n"
            + "  $('distanceBar').style.width = distPct + '%';\n"
            + "\n"
            + "  const distCard = $('cardDistance');\n"
            + "  distCard.classList.remove('green','orange','red');\n"
            + "  if(distanceValue >= 999) distCard.classList.add('green');\n"
            + "  else if(distanceValue <= (d.distanceThreshold || 30)) distCard.classList.add('red');\n"
            + "  else distCard.classList.add('orange');\n"
            + "\n"
            + "  const pc = $('presenceChip');\n"
            + "  pc.textContent = d.presence ? 'PRESENCIA' : 'Sin presencia';\n"
            + "  pc.className = 'chip ' + (d.presence ? 'on' : 'off');\n"
            + "  $('presenceRow').textContent = d.presence ? 'Detectada' : 'No detectada';\n"
            + "\n"
            + "  $('entries').textContent = d.entryCount || 0;\n"
            + "  $('entriesToday').textContent = d.entryCount || 0;\n"
            + "  $('threshold').textContent = d.occupancyThreshold || 100;\n"
            + "\n"
            + "  const occ = clamp(((d.entryCount || 0) / (d.occupancyThreshold || 100)) * 100, 0, 100);\n"
            + "  $('entryBar').style.width = occ + '%';\n"
            + "  $('occMini').textContent = occ.toFixed(0) + '%';\n"
            + "  $('occupancyRow').textContent = occ.toFixed(1) + '%';\n"
            + "\n"
            + "  const entryCard = $('cardEntry');\n"
            + "  entryCard.classList.remove('green','orange','red');\n"
            + "  if(occ >= 100) entryCard.classList.add('red');\n"
            + "  else if(occ >= 80) entryCard.classList.add('orange');\n"
            + "  else entryCard.classList.add('green');\n"
            + "\n"
            + "  $('light').textContent = d.lightIntensity || 0;\n"
            + "  $('lightBar').style.width = (d.lightIntensity || 0) + '%';\n"
            + "  $('lightState').textContent = (d.lightIntensity || 0) === 0 ? 'Apagadas' : ((d.lightIntensity || 0) === 100 ? 'Al maximo' : 'Atenuadas');\n"
            + "  $('lightRow').textContent = (d.lightIntensity || 0) + '%';\n"
            + "\n"
            + "  const alarmActive = !!d.alarmActive;\n"
            + "  $('alarm').textContent = alarmActive ? 'ACTIVA' : 'OFF';\n"
            + "  $('alarm').classList.toggle('pulse', alarmActive);\n"
            + "  $('cardAlarm').classList.toggle('red', alarmActive);\n"
            + "  $('alarmSub').textContent = alarmActive ? 'Atencion inmediata requerida' : 'Sistema normal';\n"
            + "  $('alarmRow').textContent = alarmActive ? 'Activa' : 'Inactiva';\n"
            + "  $('riskChip').textContent = alarmActive ? 'Riesgo alto' : (occ >= 80 ? 'Riesgo medio' : 'Riesgo bajo');\n"
            + "  $('riskChip').className = 'chip ' + (alarmActive ? 'on' : 'off');\n"
            + "\n"
            + "  if((d.entryCount || 0) > prevEntryCount){\n"
            + "    const newEntries = (d.entryCount || 0) - prevEntryCount;\n"
            + "    for(let i=0;i<newEntries;i++) addLiveEntryEvent(d, i+1);\n"
            + "    playEntryBeep();\n"
            + "  }\n"
            + "  prevEntryCount = d.entryCount || 0;\n"
            + "\n"
            + "  if(Array.isArray(d.actions) && d.actions.length){\n"
            + "    const log = $('actionsLog');\n"
            + "    const stamp = fmtTime(d.timestamp);\n"
            + "    d.actions.forEach(a => {\n"
            + "      const key = stamp + '|' + a;\n"
            + "      if(actionsSeen.has(key)) return;\n"
            + "      actionsSeen.add(key);\n"
            + "      const row = document.createElement('div');\n"
            + "      row.innerHTML = '<span class=\"time\">'+stamp+'</span><span class=\"ok\">&gt; '+esc(a)+'</span>';\n"
            + "      log.prepend(row);\n"
            + "    });\n"
            + "    while(log.children.length > 40) log.removeChild(log.lastChild);\n"
            + "  }\n"
            + "\n"
            + "  pushHistory(distanceHistory, distanceValue >= 999 ? 0 : distanceValue, 30);\n"
            + "  pushHistory(occupancyHistory, occ, 30);\n"
            + "  drawLineChart('distanceChart', distanceHistory, 'cm', d.distanceThreshold || 30);\n"
            + "  drawLineChart('occupancyChart', occupancyHistory, '%', 80);\n"
            + "\n"
            + "  $('lastEventMini').textContent = liveEvents.length ? liveEvents[0].time : '-';\n"
            + "}\n"
            + "\n"
            + "function addLiveEntryEvent(d, seq){\n"
            + "  const event = {\n"
            + "    time: fmtTime(d.timestamp),\n"
            + "    title: 'Ingreso detectado #' + (d.entryCount - (seq - 1)),\n"
            + "    desc: 'Distancia: ' + (Number(d.distanceCm || 0).toFixed(1)) + ' cm · Presencia: ' + (d.presence ? 'SI' : 'NO'),\n"
            + "    tag: 'ENTRADA'\n"
            + "  };\n"
            + "  liveEvents.unshift(event);\n"
            + "  while(liveEvents.length > 20) liveEvents.pop();\n"
            + "  renderLiveFeed();\n"
            + "}\n"
            + "\n"
            + "function renderLiveFeed(){\n"
            + "  const feed = $('eventFeed');\n"
            + "  $('liveCounter').textContent = liveEvents.length + ' eventos';\n"
            + "  if(!liveEvents.length){\n"
            + "    feed.innerHTML = '<div class=\"event-item\"><div class=\"event-time\">--:--:--</div><div class=\"event-main\"><strong>Sin ingresos detectados</strong><span>El sistema mostrara aqui cada nuevo acceso.</span></div><div class=\"event-tag warn\">STANDBY</div></div>';\n"
            + "    return;\n"
            + "  }\n"
            + "  feed.innerHTML = liveEvents.map(e => ''\n"
            + "    + '<div class=\"event-item\">'\n"
            + "    + '<div class=\"event-time\">'+esc(e.time)+'</div>'\n"
            + "    + '<div class=\"event-main\"><strong>'+esc(e.title)+'</strong><span>'+esc(e.desc)+'</span></div>'\n"
            + "    + '<div class=\"event-tag in\">'+esc(e.tag)+'</div>'\n"
            + "    + '</div>'\n"
            + "  ).join('');\n"
            + "}\n"
            + "\n"
            + "function pushHistory(arr, value, max){ arr.push(value); if(arr.length > max) arr.shift(); }\n"
            + "\n"
            + "function drawLineChart(canvasId, data, unit, threshold){\n"
            + "  const canvas = $(canvasId); if(!canvas) return;\n"
            + "  const ctx = canvas.getContext('2d');\n"
            + "  const w = canvas.width, h = canvas.height;\n"
            + "  ctx.clearRect(0,0,w,h);\n"
            + "\n"
            + "  const bg = ctx.createLinearGradient(0,0,0,h); bg.addColorStop(0,'#0a2913'); bg.addColorStop(1,'#03111f'); ctx.fillStyle = bg; ctx.fillRect(0,0,w,h);\n"
            + "  const pad = 30;\n"
            + "  const max = Math.max(threshold || 1, ...data, 1);\n"
            + "\n"
            + "  ctx.strokeStyle = 'rgba(232,245,233,0.14)';\n"
            + "  ctx.lineWidth = 1;\n"
            + "  for(let i=0;i<5;i++){\n"
            + "    const y = pad + ((h - pad*2) / 4) * i;\n"
            + "    ctx.beginPath(); ctx.moveTo(pad, y); ctx.lineTo(w - pad, y); ctx.stroke();\n"
            + "  }\n"
            + "\n"
            + "  if(threshold){\n"
            + "    const yT = h - pad - ((threshold / max) * (h - pad*2));\n"
            + "    ctx.strokeStyle = 'rgba(229,57,53,.85)';\n"
            + "    ctx.setLineDash([6,4]);\n"
            + "    ctx.beginPath(); ctx.moveTo(pad, yT); ctx.lineTo(w-pad, yT); ctx.stroke();\n"
            + "    ctx.setLineDash([]);\n"
            + "    ctx.fillStyle = '#ff5252'; ctx.font = 'bold 12px Segoe UI'; ctx.fillText('Umbral ' + threshold + unit, pad+6, yT-6);\n"
            + "  }\n"
            + "\n"
            + "  if(data.length < 2){\n"
            + "    ctx.fillStyle = '#ffd54f'; ctx.font = '14px Segoe UI'; ctx.fillText('Esperando mas datos...', pad, h/2);\n"
            + "    return;\n"
            + "  }\n"
            + "\n"
            + "  const areaGrad = ctx.createLinearGradient(0,0,0,h);\n"
            + "  areaGrad.addColorStop(0,'rgba(255,179,0,.35)');\n"
            + "  areaGrad.addColorStop(1,'rgba(118,255,3,.02)');\n"
            + "  ctx.beginPath();\n"
            + "  data.forEach((v,i) => {\n"
            + "    const x = pad + (i * ((w - pad*2) / Math.max(data.length - 1, 1)));\n"
            + "    const y = h - pad - ((v / max) * (h - pad*2));\n"
            + "    if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y);\n"
            + "  });\n"
            + "  ctx.lineTo(w - pad, h - pad); ctx.lineTo(pad, h - pad); ctx.closePath();\n"
            + "  ctx.fillStyle = areaGrad; ctx.fill();\n"
            + "\n"
            + "  const lineGrad = ctx.createLinearGradient(pad,0,w-pad,0);\n"
            + "  lineGrad.addColorStop(0,'#76ff03');\n"
            + "  lineGrad.addColorStop(.5,'#ffd54f');\n"
            + "  lineGrad.addColorStop(1,'#ffb300');\n"
            + "  ctx.strokeStyle = lineGrad;\n"
            + "  ctx.lineWidth = 2.8;\n"
            + "  ctx.shadowColor = 'rgba(255,179,0,.6)'; ctx.shadowBlur = 8;\n"
            + "  ctx.beginPath();\n"
            + "  data.forEach((v,i) => {\n"
            + "    const x = pad + (i * ((w - pad*2) / Math.max(data.length - 1, 1)));\n"
            + "    const y = h - pad - ((v / max) * (h - pad*2));\n"
            + "    if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y);\n"
            + "  });\n"
            + "  ctx.stroke();\n"
            + "  ctx.shadowBlur = 0;\n"
            + "\n"
            + "  const last = data[data.length - 1];\n"
            + "  const lx = w - pad;\n"
            + "  const ly = h - pad - ((last / max) * (h - pad*2));\n"
            + "  ctx.fillStyle = '#ffd700';\n"
            + "  ctx.beginPath(); ctx.arc(lx, ly, 5, 0, Math.PI*2); ctx.fill();\n"
            + "  ctx.strokeStyle = '#03111f'; ctx.lineWidth = 2; ctx.stroke();\n"
            + "  ctx.fillStyle = '#ffd54f'; ctx.font = 'bold 12px Segoe UI'; ctx.fillText(last.toFixed(1) + unit, lx - 48, ly - 10);\n"
            + "}\n"
            + "\n"
            + "async function sendCommand(ev){\n"
            + "  ev.preventDefault();\n"
            + "  const inp = $('cmdInput');\n"
            + "  const cmd = inp.value.trim();\n"
            + "  if(!cmd) return false;\n"
            + "  inp.value = '';\n"
            + "  appendCmd('> ' + cmd, 'ok');\n"
            + "  try{\n"
            + "    const r = await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cmd})});\n"
            + "    const j = await r.json();\n"
            + "    appendCmd(j.output || '(sin respuesta)', 'ok');\n"
            + "  }catch(e){\n"
            + "    appendCmd('Error: ' + e.message, 'err');\n"
            + "  }\n"
            + "  refresh();\n"
            + "  return false;\n"
            + "}\n"
            + "\n"
            + "function quick(c){ $('cmdInput').value = c; $('cmdForm').requestSubmit(); }\n"
            + "\n"
            + "function appendCmd(text, cls){\n"
            + "  const log = $('cmdLog');\n"
            + "  const row = document.createElement('div');\n"
            + "  row.className = cls || '';\n"
            + "  row.innerHTML = '<span class=\"time\">'+fmtTime(Date.now())+'</span><pre style=\"white-space:pre-wrap;display:inline;margin:0;\">'+esc(text)+'</pre>';\n"
            + "  log.prepend(row);\n"
            + "  while(log.children.length > 30) log.removeChild(log.lastChild);\n"
            + "}\n"
            + "\n"
            + "renderLiveFeed();\n"
            + "refresh();\n"
            + "setInterval(refresh, 1000);\n"
            + "document.body.addEventListener('click', ensureAudio, { once:true });\n"
            + "</script>\n"
            + "</body>\n"
            + "</html>\n";
}

