package presentacion;

/** Dashboard web con controles graficos (sin consola de texto). */
final class DashboardHtml {
    private DashboardHtml() {}

    static final String PAGE = "<!DOCTYPE html>\n"
        + "<html lang=\"es\">\n"
        + "<head>\n"
        + "<meta charset=\"UTF-8\">\n"
        + "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
        + "<title>Estadio Inteligente</title>\n"
        + "<style>\n"
        + ":root{--bg:#0d0e12;--card:#17181f;--border:#2d2f3b;--text:#e2e8f0;"
        + "      --muted:#94a3b8;--accent:#7c8cf8;--accent2:#06b6d4;"
        + "      --green:#34d399;--orange:#fbbf24;--red:#f87171;"
        + "      --cyan:#67e8f9;--purple:#c084fc;}\n"
        + "*{margin:0;padding:0;box-sizing:border-box;}\n"
        + "body{font-family:'Segoe UI',system-ui,sans-serif;background:var(--bg);"
        + "     color:var(--text);padding:20px;max-width:1500px;margin:0 auto;}\n"

        /* Header */
        + "header{padding:24px 22px;border:1px solid rgba(124,132,248,.22);border-radius:18px;"
        + "       background:linear-gradient(135deg,rgba(30,31,48,.88),rgba(19,20,26,.94));"
        + "       margin-bottom:20px;box-shadow:0 10px 30px rgba(0,0,0,.45);}\n"
        + ".hdr-row{display:flex;justify-content:space-between;align-items:flex-start;"
        + "         gap:16px;flex-wrap:wrap;}\n"
        + "h1{font-size:1.9rem;color:#7dd3fc;margin-bottom:4px;}\n"
        + ".subtitle{color:var(--muted);font-size:.93rem;}\n"
        + ".status-bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-top:12px;}\n"
        + ".badge{display:inline-flex;align-items:center;gap:7px;padding:7px 13px;"
        + "       border-radius:999px;background:rgba(13,14,18,.7);"
        + "       border:1px solid rgba(124,132,248,.18);font-size:.85rem;}\n"
        + ".dot{width:9px;height:9px;border-radius:50%;background:var(--muted);}\n"
        + ".dot.on{background:var(--green);box-shadow:0 0 10px var(--green);}\n"
        + ".dot.off{background:var(--red);box-shadow:0 0 10px var(--red);}\n"
        + ".hero-metrics{display:flex;gap:10px;flex-wrap:wrap;}\n"
        + ".hero-pill{padding:10px 14px;border-radius:13px;background:rgba(19,20,26,.85);"
        + "           border:1px solid rgba(124,132,248,.16);min-width:130px;}\n"
        + ".hero-pill .lbl{font-size:.72rem;color:var(--muted);text-transform:uppercase;"
        + "                letter-spacing:1px;}\n"
        + ".hero-pill .num{font-size:1.3rem;font-weight:700;margin-top:4px;color:var(--accent);}\n"

        /* Cards */
        + ".kpi-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));"
        + "          gap:14px;margin-bottom:18px;}\n"
        + ".card{background:linear-gradient(180deg,rgba(23,24,31,.98),rgba(19,20,26,.96));"
        + "      border:1px solid rgba(45,47,59,.8);border-radius:16px;padding:16px;"
        + "      box-shadow:0 10px 22px rgba(0,0,0,.3);position:relative;overflow:hidden;"
        + "      transition:transform .15s,border-color .15s;}\n"
        + ".card:hover{transform:translateY(-2px);border-color:#4b5470;}\n"
        + ".card h2{font-size:.75rem;letter-spacing:1px;text-transform:uppercase;"
        + "         color:var(--muted);margin-bottom:9px;}\n"
        + ".value{font-size:2.1rem;font-weight:800;line-height:1;color:var(--accent);}\n"
        + ".unit{font-size:.4em;color:var(--muted);font-weight:500;margin-left:3px;}\n"
        + ".sub{margin-top:7px;color:var(--muted);font-size:.9rem;}\n"
        + ".bar{height:8px;background:#0b1220;border-radius:999px;overflow:hidden;"
        + "     margin-top:10px;}\n"
        + ".bar>span{display:block;height:100%;width:0%;transition:width .4s;"
        + "          background:linear-gradient(90deg,var(--accent),var(--accent2));}\n"
        + ".bar.green>span{background:linear-gradient(90deg,#22c55e,#06b6d4);}\n"
        + ".bar.orange>span{background:linear-gradient(90deg,#f59e0b,#fde047);}\n"
        + ".bar.red>span{background:linear-gradient(90deg,#ef4444,#f59e0b);}\n"
        + ".chip{display:inline-flex;align-items:center;padding:4px 9px;border-radius:999px;"
        + "      font-size:.74rem;border:1px solid var(--border);background:#13141a;}\n"
        + ".chip.on{color:#6ee7b7;border-color:rgba(52,211,153,.45);}\n"
        + ".chip.off{color:var(--muted);}\n"
        + ".green .value{color:var(--green);} .orange .value{color:var(--orange);}\n"
        + ".red .value{color:var(--red);} .alarm-box{display:flex;align-items:center;"
        + "justify-content:space-between;gap:12px;}\n"
        + ".alarm-state{font-size:1.6rem;font-weight:800;}\n"
        + ".pulse{animation:pulse 1s infinite;}\n"
        + "@keyframes pulse{0%{opacity:1;transform:scale(1)}50%{opacity:.5;"
        + "transform:scale(1.04)}100%{opacity:1;transform:scale(1)}}\n"

        /* Section */
        + ".section{background:linear-gradient(180deg,rgba(23,24,31,.98),rgba(17,18,24,.97));"
        + "          border:1px solid rgba(45,47,59,.8);border-radius:16px;padding:16px;"
        + "          box-shadow:0 10px 22px rgba(0,0,0,.3);margin-bottom:16px;}\n"
        + ".sec-hdr{display:flex;justify-content:space-between;align-items:center;"
        + "         margin-bottom:12px;flex-wrap:wrap;gap:8px;}\n"
        + ".sec-hdr h3{font-size:.78rem;letter-spacing:1px;text-transform:uppercase;"
        + "            color:var(--muted);}\n"

        /* Mode buttons */
        + ".mode-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;}\n"
        + "@media(max-width:900px){.mode-grid{grid-template-columns:repeat(3,1fr);}}\n"
        + ".mode-btn{cursor:pointer;padding:14px 6px;border-radius:12px;"
        + "          border:1px solid rgba(45,47,59,.9);background:rgba(19,20,26,.9);"
        + "          color:var(--muted);font-size:.82rem;font-weight:700;font-family:inherit;"
        + "          text-align:center;transition:all .18s;line-height:1.3;}\n"
        + ".mode-btn:hover{transform:translateY(-2px);filter:brightness(1.35);}\n"
        + ".mode-btn.active{border-width:2px;filter:brightness(1.5);"
        + "                 box-shadow:0 0 16px currentColor;}\n"
        + ".mode-btn.partido{color:#34d399;border-color:rgba(52,211,153,.4);}\n"
        + ".mode-btn.train{color:#67e8f9;border-color:rgba(103,232,249,.4);}\n"
        + ".mode-btn.show{color:#c084fc;border-color:rgba(192,132,252,.4);"
        + "               background:rgba(88,28,135,.15);}\n"
        + ".mode-btn.event{color:#fbbf24;border-color:rgba(251,191,36,.4);}\n"
        + ".mode-btn.emerg{color:#f87171;border-color:rgba(248,113,113,.4);}\n"
        + ".mode-btn.manual{color:#94a3b8;border-color:rgba(148,163,184,.3);}\n"
        + ".mode-btn.auto{color:#a5b4fc;border-color:rgba(165,180,252,.3);}\n"

        /* Sliders */
        + "input[type=range]{-webkit-appearance:none;width:100%;height:5px;"
        + "                  background:#1a1b2e;border-radius:999px;outline:none;"
        + "                  cursor:pointer;margin:0;}\n"
        + "input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:16px;"
        + "    height:16px;border-radius:50%;background:var(--accent);cursor:pointer;"
        + "    box-shadow:0 0 8px var(--accent);transition:transform .1s;}\n"
        + "input[type=range]::-webkit-slider-thumb:hover{transform:scale(1.2);}\n"
        + "input[type=range]::-moz-range-thumb{width:16px;height:16px;border:none;"
        + "    border-radius:50%;background:var(--accent);cursor:pointer;}\n"

        /* Global light control */
        + ".light-ctrl{display:flex;align-items:center;gap:12px;padding:12px 14px;"
        + "            background:rgba(13,14,18,.6);border-radius:11px;"
        + "            border:1px solid rgba(45,47,59,.8);margin-bottom:14px;}\n"
        + ".light-ctrl .lbl{font-size:.75rem;color:var(--muted);text-transform:uppercase;"
        + "                  letter-spacing:1px;min-width:90px;}\n"
        + ".light-ctrl input{flex:1;}\n"
        + ".light-ctrl .val{font-size:.95rem;font-weight:700;color:var(--orange);min-width:38px;"
        + "                  text-align:right;}\n"
        + ".quick-btns{display:flex;gap:8px;margin-bottom:14px;}\n"
        + ".ctrl-btn{flex:1;padding:9px 6px;border-radius:10px;"
        + "          border:1px solid rgba(45,47,59,.9);background:#13141a;"
        + "          color:var(--muted);font-size:.78rem;font-weight:700;"
        + "          cursor:pointer;font-family:inherit;transition:all .15s;}\n"
        + ".ctrl-btn:hover{filter:brightness(1.35);border-color:#7c8cf8;}\n"

        /* Zone cards */
        + ".zone-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;}\n"
        + "@media(max-width:800px){.zone-grid{grid-template-columns:repeat(3,1fr);}}\n"
        + ".zone-card{background:rgba(19,20,26,.9);border:1px solid rgba(45,47,59,.8);"
        + "           border-radius:14px;padding:12px 10px;text-align:center;"
        + "           transition:border-color .3s;}\n"
        + ".zone-circle{width:44px;height:44px;border-radius:50%;background:#1a1b2e;"
        + "             margin:0 auto 8px;transition:background .4s,box-shadow .4s;}\n"
        + ".zone-name{font-size:.67rem;color:var(--muted);text-transform:uppercase;"
        + "           letter-spacing:1px;margin-bottom:5px;}\n"
        + ".zone-pct{font-size:1.1rem;font-weight:800;color:var(--accent);"
        + "          line-height:1;margin-bottom:8px;}\n"
        + ".zone-slider-row{display:flex;align-items:center;gap:6px;margin-top:6px;}\n"
        + ".zone-slider-row input{flex:1;}\n"

        /* Alarm button */
        + ".alarm-btn{width:100%;padding:18px;border-radius:14px;font-size:1rem;"
        + "           font-weight:700;cursor:pointer;font-family:inherit;transition:all .2s;"
        + "           border:2px solid rgba(248,113,113,.4);background:rgba(239,68,68,.08);"
        + "           color:var(--red);margin-bottom:12px;}\n"
        + ".alarm-btn.activa{background:rgba(239,68,68,.22);"
        + "                  border-color:rgba(248,113,113,.85);"
        + "                  box-shadow:0 0 22px rgba(239,68,68,.3);"
        + "                  animation:pulse 1s infinite;}\n"
        + ".alarm-btn.inactiva{color:var(--green);border-color:rgba(52,211,153,.4);"
        + "                    background:rgba(52,211,153,.08);}\n"

        /* Main layout */
        + ".main-grid{display:grid;grid-template-columns:1.45fr 1fr;gap:16px;margin-bottom:18px;}\n"
        + "@media(max-width:1100px){.main-grid{grid-template-columns:1fr;}}\n"

        /* Events & table */
        + ".event-feed{display:flex;flex-direction:column;gap:9px;max-height:320px;"
        + "            overflow:auto;}\n"
        + ".event-item{display:grid;grid-template-columns:88px 1fr auto;gap:10px;"
        + "            align-items:center;padding:11px;border-radius:12px;"
        + "            background:rgba(21,22,30,.9);border:1px solid rgba(45,47,59,.9);}\n"
        + ".event-time{font-family:Consolas,monospace;color:#67e8f9;font-size:.88rem;}\n"
        + ".event-main strong{display:block;color:#f8fafc;font-size:.9rem;margin-bottom:3px;}\n"
        + ".event-main span{color:var(--muted);font-size:.82rem;}\n"
        + ".event-tag{padding:5px 9px;border-radius:999px;font-size:.72rem;font-weight:700;}\n"
        + ".event-tag.in{color:#6ee7b7;border:1px solid rgba(52,211,153,.35);"
        + "              background:rgba(6,78,59,.28);}\n"
        + ".event-tag.warn{color:#fde047;border:1px solid rgba(251,191,36,.35);"
        + "                background:rgba(78,63,10,.24);}\n"
        + "table{width:100%;border-collapse:collapse;}\n"
        + "th,td{padding:9px 11px;border-bottom:1px solid rgba(148,163,184,.1);"
        + "      text-align:left;font-size:.88rem;}\n"
        + "th{color:#a5b4fc;font-weight:700;background:rgba(19,20,26,.7);}\n"
        + "td{color:#e2e8f0;}\n"
        + ".log{background:#0a0b0f;border:1px solid var(--border);border-radius:10px;"
        + "     padding:10px;font-family:Consolas,monospace;font-size:.84rem;"
        + "     max-height:200px;overflow-y:auto;}\n"
        + ".log div{padding:3px 0;border-bottom:1px dashed rgba(255,255,255,.05);"
        + "         word-break:break-word;}\n"
        + ".ts{color:var(--muted);margin-right:6px;}\n"
        + ".ok{color:var(--green);} .warn{color:var(--orange);} .err{color:var(--red);}\n"
        + ".canvas-wrap{background:#0b0c11;border:1px solid rgba(45,47,59,.8);"
        + "             border-radius:12px;padding:12px;height:220px;}\n"
        + "canvas{width:100%;height:100%;display:block;}\n"
        + "footer{text-align:center;color:var(--muted);font-size:.8rem;padding:16px 0;}\n"
        + "</style>\n"
        + "</head>\n"
        + "<body>\n"

        /* ===== HEADER ===== */
        + "<header>\n"
        + "  <div class=\"hdr-row\">\n"
        + "    <div>\n"
        + "      <h1>Estadio Inteligente</h1>\n"
        + "      <div class=\"subtitle\">Sistema de monitoreo y control &middot; Arduino + HC-SR04 + WS2812B</div>\n"
        + "      <div class=\"status-bar\">\n"
        + "        <span class=\"badge\"><span id=\"hwDot\" class=\"dot\"></span>"
        + "<span id=\"hwText\">Conectando...</span></span>\n"
        + "        <span class=\"badge\">Modo: <strong id=\"modeText\">-</strong></span>\n"
        + "        <span class=\"badge\">Actualizado: <span id=\"lastUpdate\">-</span></span>\n"
        + "      </div>\n"
        + "    </div>\n"
        + "    <div class=\"hero-metrics\">\n"
        + "      <div class=\"hero-pill\"><div class=\"lbl\">Ingresos</div>"
        + "<div class=\"num\" id=\"entriesToday\">0</div></div>\n"
        + "      <div class=\"hero-pill\"><div class=\"lbl\">Ocupacion</div>"
        + "<div class=\"num\" id=\"occMini\">0%</div></div>\n"
        + "      <div class=\"hero-pill\"><div class=\"lbl\">Ultimo ingreso</div>"
        + "<div class=\"num\" id=\"lastEventMini\">-</div></div>\n"
        + "    </div>\n"
        + "  </div>\n"
        + "</header>\n"

        /* ===== KPI CARDS ===== */
        + "<div class=\"kpi-grid\">\n"
        + "  <div class=\"card\" id=\"cardDistance\">\n"
        + "    <h2>Sensor de presencia <span class=\"chip\" id=\"presenceChip\">-</span></h2>\n"
        + "    <div class=\"value\"><span id=\"distance\">--</span>"
        + "<span class=\"unit\">cm</span></div>\n"
        + "    <div class=\"sub\" id=\"distanceDesc\">Sin datos</div>\n"
        + "    <div class=\"bar green\"><span id=\"distanceBar\"></span></div>\n"
        + "  </div>\n"
        + "  <div class=\"card\" id=\"cardEntry\">\n"
        + "    <h2>Aforo acumulado</h2>\n"
        + "    <div class=\"value\"><span id=\"entries\">0</span>"
        + "<span class=\"unit\">/ <span id=\"threshold\">100</span></span></div>\n"
        + "    <div class=\"sub\">personas registradas</div>\n"
        + "    <div class=\"bar\"><span id=\"entryBar\"></span></div>\n"
        + "  </div>\n"
        + "  <div class=\"card\" id=\"cardLight\">\n"
        + "    <h2>Iluminacion promedio</h2>\n"
        + "    <div class=\"value\"><span id=\"light\">0</span>"
        + "<span class=\"unit\">%</span></div>\n"
        + "    <div class=\"sub\" id=\"lightState\">Apagadas</div>\n"
        + "    <div class=\"bar orange\"><span id=\"lightBar\"></span></div>\n"
        + "  </div>\n"
        + "  <div class=\"card\" id=\"cardAlarm\">\n"
        + "    <h2>Alarma</h2>\n"
        + "    <div class=\"alarm-box\">\n"
        + "      <div><div class=\"alarm-state\" id=\"alarm\">OFF</div>"
        + "<div class=\"sub\" id=\"alarmSub\">Sistema normal</div></div>\n"
        + "      <div class=\"chip\" id=\"riskChip\">Riesgo bajo</div>\n"
        + "    </div>\n"
        + "  </div>\n"
        + "</div>\n"

        /* ===== MODE PANEL ===== */
        + "<div class=\"section\" style=\"margin-bottom:18px;\">\n"
        + "  <div class=\"sec-hdr\">\n"
        + "    <h3>Modo de operacion</h3>\n"
        + "    <span class=\"chip\">Selecciona un modo para activarlo</span>\n"
        + "  </div>\n"
        + "  <div class=\"mode-grid\">\n"
        + "    <button id=\"btn_PARTIDO\" class=\"mode-btn partido\""
        + " onclick=\"setMode('PARTIDO')\">&#9917; Partido</button>\n"
        + "    <button id=\"btn_ENTRENAMIENTO\" class=\"mode-btn train\""
        + " onclick=\"setMode('ENTRENAMIENTO')\">&#128293; Entrenamiento</button>\n"
        + "    <button id=\"btn_SHOW\" class=\"mode-btn show\""
        + " onclick=\"setMode('SHOW')\">&#127937; Show!</button>\n"
        + "    <button id=\"btn_EVENTO\" class=\"mode-btn event\""
        + " onclick=\"setMode('EVENTO')\">&#127882; Evento</button>\n"
        + "    <button id=\"btn_EMERGENCY\" class=\"mode-btn emerg\""
        + " onclick=\"setMode('EMERGENCY')\">&#128680; Emergencia</button>\n"
        + "    <button id=\"btn_MANUAL\" class=\"mode-btn manual\""
        + " onclick=\"setMode('MANUAL')\">&#9881; Manual</button>\n"
        + "  </div>\n"
        + "</div>\n"

        /* ===== MAIN GRID ===== */
        + "<div class=\"main-grid\">\n"

        /* --- LEFT COLUMN --- */
        + "  <div>\n"

        /* Zone + Light control */
        + "    <div class=\"section\">\n"
        + "      <div class=\"sec-hdr\">\n"
        + "        <h3>Control de iluminacion por zona</h3>\n"
        + "        <span class=\"chip\">Manual: arrastra los sliders</span>\n"
        + "      </div>\n"
        /* Global light slider */
        + "      <div class=\"light-ctrl\">\n"
        + "        <span class=\"lbl\">Brillo global</span>\n"
        + "        <input type=\"range\" id=\"globalLight\" min=\"0\" max=\"100\" value=\"0\""
        + " oninput=\"lightSlider(this.value)\">\n"
        + "        <span class=\"val\" id=\"globalLightVal\">0%</span>\n"
        + "      </div>\n"
        /* Quick light buttons */
        + "      <div class=\"quick-btns\">\n"
        + "        <button class=\"ctrl-btn\" onclick=\"setAllLight(0)\">Apagar todo</button>\n"
        + "        <button class=\"ctrl-btn\" onclick=\"setAllLight(25)\">25%</button>\n"
        + "        <button class=\"ctrl-btn\" onclick=\"setAllLight(50)\">50%</button>\n"
        + "        <button class=\"ctrl-btn\" onclick=\"setAllLight(75)\">75%</button>\n"
        + "        <button class=\"ctrl-btn\" onclick=\"setAllLight(100)\">Maximo</button>\n"
        + "      </div>\n"
        /* Zone cards */
        + "      <div class=\"zone-grid\">\n"

        + "        <div class=\"zone-card\">\n"
        + "          <div class=\"zone-circle\" id=\"zc_NORTE\"></div>\n"
        + "          <div class=\"zone-name\">Norte</div>\n"
        + "          <div class=\"zone-pct\" id=\"zp_NORTE\">0%</div>\n"
        + "          <div class=\"bar\"><span id=\"zb_NORTE\"></span></div>\n"
        + "          <div class=\"zone-slider-row\">\n"
        + "            <input type=\"range\" id=\"zs_NORTE\" min=\"0\" max=\"100\" value=\"0\""
        + " oninput=\"zoneSlider('NORTE',this.value)\">\n"
        + "          </div>\n"
        + "        </div>\n"

        + "        <div class=\"zone-card\">\n"
        + "          <div class=\"zone-circle\" id=\"zc_SUR\"></div>\n"
        + "          <div class=\"zone-name\">Sur</div>\n"
        + "          <div class=\"zone-pct\" id=\"zp_SUR\">0%</div>\n"
        + "          <div class=\"bar\"><span id=\"zb_SUR\"></span></div>\n"
        + "          <div class=\"zone-slider-row\">\n"
        + "            <input type=\"range\" id=\"zs_SUR\" min=\"0\" max=\"100\" value=\"0\""
        + " oninput=\"zoneSlider('SUR',this.value)\">\n"
        + "          </div>\n"
        + "        </div>\n"

        + "        <div class=\"zone-card\">\n"
        + "          <div class=\"zone-circle\" id=\"zc_ORIENTAL\"></div>\n"
        + "          <div class=\"zone-name\">Oriental</div>\n"
        + "          <div class=\"zone-pct\" id=\"zp_ORIENTAL\">0%</div>\n"
        + "          <div class=\"bar\"><span id=\"zb_ORIENTAL\"></span></div>\n"
        + "          <div class=\"zone-slider-row\">\n"
        + "            <input type=\"range\" id=\"zs_ORIENTAL\" min=\"0\" max=\"100\" value=\"0\""
        + " oninput=\"zoneSlider('ORIENTAL',this.value)\">\n"
        + "          </div>\n"
        + "        </div>\n"

        + "        <div class=\"zone-card\">\n"
        + "          <div class=\"zone-circle\" id=\"zc_OCCIDENTAL\"></div>\n"
        + "          <div class=\"zone-name\">Occidental</div>\n"
        + "          <div class=\"zone-pct\" id=\"zp_OCCIDENTAL\">0%</div>\n"
        + "          <div class=\"bar\"><span id=\"zb_OCCIDENTAL\"></span></div>\n"
        + "          <div class=\"zone-slider-row\">\n"
        + "            <input type=\"range\" id=\"zs_OCCIDENTAL\" min=\"0\" max=\"100\" value=\"0\""
        + " oninput=\"zoneSlider('OCCIDENTAL',this.value)\">\n"
        + "          </div>\n"
        + "        </div>\n"

        + "        <div class=\"zone-card\">\n"
        + "          <div class=\"zone-circle\" id=\"zc_CANCHA\"></div>\n"
        + "          <div class=\"zone-name\">Cancha</div>\n"
        + "          <div class=\"zone-pct\" id=\"zp_CANCHA\">0%</div>\n"
        + "          <div class=\"bar\"><span id=\"zb_CANCHA\"></span></div>\n"
        + "          <div class=\"zone-slider-row\">\n"
        + "            <input type=\"range\" id=\"zs_CANCHA\" min=\"0\" max=\"100\" value=\"0\""
        + " oninput=\"zoneSlider('CANCHA',this.value)\">\n"
        + "          </div>\n"
        + "        </div>\n"

        + "      </div>\n"  /* /zone-grid */
        + "    </div>\n"    /* /section zone control */

        /* Occupancy chart */
        + "    <div class=\"section\">\n"
        + "      <div class=\"sec-hdr\">\n"
        + "        <h3>Aforo en tiempo real</h3>\n"
        + "        <span class=\"chip\">Ultimos 30 puntos</span>\n"
        + "      </div>\n"
        + "      <div class=\"canvas-wrap\">"
        + "<canvas id=\"occupancyChart\" width=\"800\" height=\"200\"></canvas></div>\n"
        + "    </div>\n"

        /* Actions log */
        + "    <div class=\"section\">\n"
        + "      <div class=\"sec-hdr\"><h3>Registro de acciones</h3>"
        + "<span class=\"chip\">Automatico</span></div>\n"
        + "      <div class=\"log\" id=\"actionsLog\">"
        + "<div class=\"ts\">Esperando datos...</div></div>\n"
        + "    </div>\n"

        + "  </div>\n"  /* /left column */

        /* --- RIGHT COLUMN --- */
        + "  <div>\n"

        /* Alarm control */
        + "    <div class=\"section\">\n"
        + "      <div class=\"sec-hdr\"><h3>Control de alarma</h3></div>\n"
        + "      <button id=\"alarmBtn\" class=\"alarm-btn inactiva\""
        + " onclick=\"toggleAlarm()\">&#128276; Activar alarma</button>\n"
        + "      <div style=\"font-size:.8rem;color:var(--muted);text-align:center;"
        + "           padding:4px 0\" id=\"alarmDetail\">Sistema en estado normal</div>\n"
        + "    </div>\n"

        /* Live events */
        + "    <div class=\"section\">\n"
        + "      <div class=\"sec-hdr\">\n"
        + "        <h3>Ingresos detectados</h3>\n"
        + "        <span class=\"chip\" id=\"liveCounter\">0 eventos</span>\n"
        + "      </div>\n"
        + "      <div class=\"event-feed\" id=\"eventFeed\"></div>\n"
        + "    </div>\n"

        /* Snapshot table */
        + "    <div class=\"section\">\n"
        + "      <div class=\"sec-hdr\"><h3>Estado actual</h3>"
        + "<span class=\"chip\">Snapshot</span></div>\n"
        + "      <table>\n"
        + "        <thead><tr><th>Indicador</th><th>Valor</th></tr></thead>\n"
        + "        <tbody>\n"
        + "          <tr><td>Presencia</td><td id=\"presenceRow\">-</td></tr>\n"
        + "          <tr><td>Distancia</td><td id=\"distanceRow\">-</td></tr>\n"
        + "          <tr><td>Ocupacion</td><td id=\"occupancyRow\">-</td></tr>\n"
        + "          <tr><td>Iluminacion</td><td id=\"lightRow\">-</td></tr>\n"
        + "          <tr><td>Alarma</td><td id=\"alarmRow\">-</td></tr>\n"
        + "        </tbody>\n"
        + "      </table>\n"
        + "    </div>\n"

        + "  </div>\n"  /* /right column */
        + "</div>\n"    /* /main-grid */

        + "<footer>Dashboard actualizado cada segundo &middot; Estadio Inteligente</footer>\n"

        /* ===== JAVASCRIPT ===== */
        + "<script>\n"
        + "const $ = id => document.getElementById(id);\n"
        + "const liveEvents = [];\n"
        + "const occupancyHistory = [];\n"
        + "const actionsSeen = new Set();\n"
        + "let prevEntryCount = 0;\n"
        + "let alarmState = false;\n"
        + "let debTimer = null;\n"
        + "let audioCtx = null;\n"
        + "\n"
        + "function fmtTime(ts){ return new Date(ts).toLocaleTimeString(); }\n"
        + "function clamp(v,a,b){ return Math.max(a,Math.min(b,v)); }\n"
        + "function esc(s){ return String(s).replace(/[&<>\"']/g,"
        + "c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c])); }\n"
        + "\n"
        /* Audio */
        + "function ensureAudio(){\n"
        + "  if(!audioCtx){ const C=window.AudioContext||window.webkitAudioContext;"
        + " if(C) audioCtx=new C(); }\n"
        + "}\n"
        + "function playEntryBeep(){\n"
        + "  try{ ensureAudio(); if(!audioCtx) return;\n"
        + "    const t=audioCtx.currentTime, o=audioCtx.createOscillator(),"
        + " g=audioCtx.createGain();\n"
        + "    o.type='sine'; o.frequency.setValueAtTime(880,t);\n"
        + "    g.gain.setValueAtTime(0.0001,t);\n"
        + "    g.gain.exponentialRampToValueAtTime(0.05,t+0.01);\n"
        + "    g.gain.exponentialRampToValueAtTime(0.0001,t+0.12);\n"
        + "    o.connect(g); g.connect(audioCtx.destination);\n"
        + "    o.start(t); o.stop(t+0.13);\n"
        + "  }catch(e){}\n"
        + "}\n"
        + "\n"
        /* Core command sender */
        + "async function sendCmd(cmd){\n"
        + "  try{\n"
        + "    await fetch('/api/command',{method:'POST',"
        + "headers:{'Content-Type':'application/json'},"
        + "body:JSON.stringify({cmd})});\n"
        + "    refresh();\n"
        + "  }catch(e){}\n"
        + "}\n"
        + "function debounce(cmd){ clearTimeout(debTimer);"
        + " debTimer=setTimeout(()=>sendCmd(cmd),250); }\n"
        + "\n"
        /* Controls */
        + "function setMode(m){ sendCmd('MODE '+m); }\n"
        + "function setAllLight(v){ $('globalLight').value=v;"
        + " $('globalLightVal').textContent=v+'%'; sendCmd('LIGHT '+v); }\n"
        + "function lightSlider(v){ $('globalLightVal').textContent=v+'%';"
        + " debounce('LIGHT '+v); }\n"
        + "function zoneSlider(z,v){\n"
        + "  $('zp_'+z).textContent=v+'%';\n"
        + "  $('zb_'+z).style.width=v+'%';\n"
        + "  debounce('ZONE '+z+' '+v);\n"
        + "}\n"
        + "function toggleAlarm(){\n"
        + "  alarmState=!alarmState;\n"
        + "  sendCmd('ALARM '+(alarmState?'ON':'OFF'));\n"
        + "}\n"
        + "\n"
        /* Refresh */
        + "async function refresh(){\n"
        + "  try{\n"
        + "    const r=await fetch('/api/status',{cache:'no-store'});\n"
        + "    if(!r.ok) throw new Error();\n"
        + "    render(await r.json());\n"
        + "  }catch(e){\n"
        + "    $('hwDot').className='dot off';\n"
        + "    $('hwText').textContent='Sin conexion al backend';\n"
        + "  }\n"
        + "}\n"
        + "\n"
        /* Render */
        + "function render(d){\n"
        /* Hardware status */
        + "  $('hwDot').className='dot '+(d.hardwareConnected?'on':'off');\n"
        + "  $('hwText').textContent=d.hardwareConnected?'Hardware conectado':'Hardware desconectado';\n"
        + "  $('modeText').textContent=d.mode||'-';\n"
        + "  $('lastUpdate').textContent=fmtTime(d.timestamp);\n"
        /* Distance card */
        + "  const dv=Number(d.distanceCm||0);\n"
        + "  const dtxt=dv>=999?'Sin objeto':dv.toFixed(1);\n"
        + "  $('distance').textContent=dtxt;\n"
        + "  $('distanceDesc').textContent=d.distanceDesc||'-';\n"
        + "  $('distanceRow').textContent=dtxt+(dv>=999?'':' cm');\n"
        + "  const dpct=dv>=999?0:clamp(100-((dv/(d.distanceThreshold||100))*100),0,100);\n"
        + "  $('distanceBar').style.width=dpct+'%';\n"
        + "  const dc=$('cardDistance');\n"
        + "  dc.classList.remove('green','orange','red');\n"
        + "  dc.classList.add(dv>=999?'green':dv<=(d.distanceThreshold||30)?'red':'orange');\n"
        + "  const pc=$('presenceChip');\n"
        + "  pc.textContent=d.presence?'PRESENCIA':'Sin presencia';\n"
        + "  pc.className='chip '+(d.presence?'on':'off');\n"
        + "  $('presenceRow').textContent=d.presence?'Detectada':'No detectada';\n"
        /* Entry card */
        + "  $('entries').textContent=d.entryCount||0;\n"
        + "  $('entriesToday').textContent=d.entryCount||0;\n"
        + "  $('threshold').textContent=d.occupancyThreshold||100;\n"
        + "  const occ=clamp(((d.entryCount||0)/(d.occupancyThreshold||100))*100,0,100);\n"
        + "  $('entryBar').style.width=occ+'%';\n"
        + "  $('occMini').textContent=occ.toFixed(0)+'%';\n"
        + "  $('occupancyRow').textContent=occ.toFixed(1)+'%';\n"
        + "  const ec=$('cardEntry');\n"
        + "  ec.classList.remove('green','orange','red');\n"
        + "  ec.classList.add(occ>=100?'red':occ>=80?'orange':'green');\n"
        /* Light card */
        + "  const li=d.lightIntensity||0;\n"
        + "  $('light').textContent=li;\n"
        + "  $('lightBar').style.width=li+'%';\n"
        + "  $('lightState').textContent=li===0?'Apagadas':li===100?'Al maximo':'Atenuadas';\n"
        + "  $('lightRow').textContent=li+'%';\n"
        + "  const gs=$('globalLight');\n"
        + "  if(gs&&!gs.matches(':active')){ gs.value=li;"
        + " $('globalLightVal').textContent=li+'%'; }\n"
        /* Alarm card */
        + "  alarmState=!!d.alarmActive;\n"
        + "  const aa=alarmState;\n"
        + "  $('alarm').textContent=aa?'ACTIVA':'OFF';\n"
        + "  $('alarm').classList.toggle('pulse',aa);\n"
        + "  $('cardAlarm').classList.toggle('red',aa);\n"
        + "  $('alarmSub').textContent=aa?'Atencion inmediata':'Sistema normal';\n"
        + "  $('alarmRow').textContent=aa?'Activa':'Inactiva';\n"
        + "  $('riskChip').textContent=aa?'Riesgo alto':occ>=80?'Riesgo medio':'Riesgo bajo';\n"
        + "  $('riskChip').className='chip '+(aa?'on':'off');\n"
        + "  $('alarmBtn').textContent=aa?'\\uD83D\\uDD14 Desactivar alarma':"
        + "'\\uD83D\\uDD14 Activar alarma';\n"
        + "  $('alarmBtn').className='alarm-btn '+(aa?'activa':'inactiva');\n"
        + "  $('alarmDetail').textContent=aa?"
        + "'Alarma activa — haga clic para desactivar':"
        + "'Sistema normal — haga clic para activar';\n"
        /* Mode buttons highlight */
        + "  ['btn_PARTIDO','btn_ENTRENAMIENTO','btn_SHOW','btn_EVENTO',"
        + "'btn_EMERGENCY','btn_MANUAL','btn_AUTO'].forEach(function(id){"
        + "var el=$(id);if(el)el.classList.remove('active');});\n"
        + "  var mmap={'PARTIDO':'btn_PARTIDO','ENTRENAMIENTO':'btn_ENTRENAMIENTO',"
        + "'SHOW':'btn_SHOW','EVENTO':'btn_EVENTO','EMERGENCY':'btn_EMERGENCY',"
        + "'MANUAL':'btn_MANUAL','AUTO':'btn_AUTO'};\n"
        + "  var activeBtn=mmap[d.mode];\n"
        + "  if(activeBtn&&$(activeBtn)) $(activeBtn).classList.add('active');\n"
        /* Zones */
        + "  if(Array.isArray(d.zones)){\n"
        + "    d.zones.forEach(function(z){\n"
        + "      var circle=$('zc_'+z.name), bar=$('zb_'+z.name),"
        + " pct=$('zp_'+z.name), sl=$('zs_'+z.name);\n"
        + "      if(circle){\n"
        + "        circle.style.background=z.active?z.color:'#1a1b2e';\n"
        + "        circle.style.boxShadow=z.active?'0 0 16px '+z.color:'none';\n"
        + "      }\n"
        + "      if(bar) bar.style.width=z.intensity+'%';\n"
        + "      if(pct) pct.textContent=z.intensity+'%';\n"
        + "      if(sl&&!sl.matches(':active')) sl.value=z.intensity;\n"
        + "    });\n"
        + "  }\n"
        /* New entries */
        + "  if((d.entryCount||0)>prevEntryCount){\n"
        + "    var ne=(d.entryCount||0)-prevEntryCount;\n"
        + "    for(var i=0;i<ne;i++) addLiveEvent(d,i+1);\n"
        + "    playEntryBeep();\n"
        + "  }\n"
        + "  prevEntryCount=d.entryCount||0;\n"
        /* Actions log */
        + "  if(Array.isArray(d.actions)&&d.actions.length){\n"
        + "    var log=$('actionsLog'), stamp=fmtTime(d.timestamp);\n"
        + "    d.actions.forEach(function(a){\n"
        + "      var key=stamp+'|'+a; if(actionsSeen.has(key)) return;\n"
        + "      actionsSeen.add(key);\n"
        + "      var row=document.createElement('div');\n"
        + "      row.innerHTML='<span class=\"ts\">'+stamp+'</span>"
        + "<span class=\"ok\">&gt; '+esc(a)+'</span>';\n"
        + "      log.prepend(row);\n"
        + "    });\n"
        + "    while(log.children.length>40) log.removeChild(log.lastChild);\n"
        + "  }\n"
        /* Occupancy chart */
        + "  occupancyHistory.push(occ);\n"
        + "  if(occupancyHistory.length>30) occupancyHistory.shift();\n"
        + "  drawChart('occupancyChart',occupancyHistory,'%',80);\n"
        + "  $('lastEventMini').textContent=liveEvents.length?liveEvents[0].time:'-';\n"
        + "}\n"
        + "\n"
        /* Live events */
        + "function addLiveEvent(d,seq){\n"
        + "  liveEvents.unshift({time:fmtTime(d.timestamp),"
        + "title:'Ingreso #'+(d.entryCount-(seq-1)),"
        + "desc:'Distancia: '+Number(d.distanceCm||0).toFixed(1)+' cm'});\n"
        + "  while(liveEvents.length>20) liveEvents.pop();\n"
        + "  renderFeed();\n"
        + "}\n"
        + "function renderFeed(){\n"
        + "  var feed=$('eventFeed');\n"
        + "  $('liveCounter').textContent=liveEvents.length+' eventos';\n"
        + "  if(!liveEvents.length){\n"
        + "    feed.innerHTML='<div class=\"event-item\"><div class=\"event-time\">--:--:--"
        + "</div><div class=\"event-main\"><strong>Sin ingresos aun</strong>"
        + "<span>Esperando deteccion...</span></div>"
        + "<div class=\"event-tag warn\">STANDBY</div></div>';\n"
        + "    return;\n"
        + "  }\n"
        + "  feed.innerHTML=liveEvents.map(function(e){\n"
        + "    return '<div class=\"event-item\">'"
        + "+'<div class=\"event-time\">'+esc(e.time)+'</div>'"
        + "+'<div class=\"event-main\"><strong>'+esc(e.title)+'</strong>'"
        + "+'<span>'+esc(e.desc)+'</span></div>'"
        + "+'<div class=\"event-tag in\">ENTRADA</div></div>';\n"
        + "  }).join('');\n"
        + "}\n"
        + "\n"
        /* Chart */
        + "function drawChart(id,data,unit,threshold){\n"
        + "  var canvas=$(id); if(!canvas) return;\n"
        + "  var ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;\n"
        + "  ctx.clearRect(0,0,w,h);\n"
        + "  var bg=ctx.createLinearGradient(0,0,0,h);\n"
        + "  bg.addColorStop(0,'#0b0c11'); bg.addColorStop(1,'#080910');\n"
        + "  ctx.fillStyle=bg; ctx.fillRect(0,0,w,h);\n"
        + "  var pad=28, mx=Math.max(threshold||1,...data,1);\n"
        + "  ctx.strokeStyle='rgba(148,163,184,.1)'; ctx.lineWidth=1;\n"
        + "  for(var i=0;i<4;i++){\n"
        + "    var y=pad+((h-pad*2)/3)*i;\n"
        + "    ctx.beginPath(); ctx.moveTo(pad,y); ctx.lineTo(w-pad,y); ctx.stroke();\n"
        + "  }\n"
        + "  if(threshold){\n"
        + "    var yT=h-pad-((threshold/mx)*(h-pad*2));\n"
        + "    ctx.strokeStyle='rgba(255,212,71,.7)'; ctx.setLineDash([5,4]);\n"
        + "    ctx.beginPath(); ctx.moveTo(pad,yT); ctx.lineTo(w-pad,yT); ctx.stroke();\n"
        + "    ctx.setLineDash([]); ctx.fillStyle='#ffe066';\n"
        + "    ctx.font='11px Segoe UI';\n"
        + "    ctx.fillText('Umbral '+threshold+unit,pad+4,yT-5);\n"
        + "  }\n"
        + "  if(data.length<2){\n"
        + "    ctx.fillStyle='#94a3b8'; ctx.font='13px Segoe UI';\n"
        + "    ctx.fillText('Recopilando datos...',pad,h/2); return;\n"
        + "  }\n"
        + "  ctx.strokeStyle='#7c8cf8'; ctx.lineWidth=2.2;\n"
        + "  ctx.beginPath();\n"
        + "  data.forEach(function(v,i){\n"
        + "    var x=pad+(i*((w-pad*2)/Math.max(data.length-1,1)));\n"
        + "    var y=h-pad-((v/mx)*(h-pad*2));\n"
        + "    i===0?ctx.moveTo(x,y):ctx.lineTo(x,y);\n"
        + "  });\n"
        + "  ctx.stroke();\n"
        + "  var lv=data[data.length-1],lx=w-pad,ly=h-pad-((lv/mx)*(h-pad*2));\n"
        + "  ctx.fillStyle='#7c8cf8';\n"
        + "  ctx.beginPath(); ctx.arc(lx,ly,4,0,Math.PI*2); ctx.fill();\n"
        + "  ctx.fillStyle='#f3f7f2'; ctx.font='11px Segoe UI';\n"
        + "  ctx.fillText(lv.toFixed(0)+unit,lx-38,ly-8);\n"
        + "}\n"
        + "\n"
        + "renderFeed();\n"
        + "refresh();\n"
        + "setInterval(refresh,1000);\n"
        + "document.body.addEventListener('click',ensureAudio,{once:true});\n"
        + "</script>\n"
        + "</body>\n"
        + "</html>\n";
}
